[development]
address = "localhost"
port = "8000"
workers = 4

[development.database]
adapter = "postgresql"
db_name = "blog_development"
pool = 5

[staging]
address = "172.16.0.12"
port = "9000"

[staging.database]
adapter = "postgresql"
db_name = "blog_development"
pool = 5


[production]
address = "172.16.0.12"
port = "9000"

[production.database]
adapter = "postgresql"
db_name = "blog_development"
pool = 5